apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "tenant.openshift.io/v1alpha1",
          "kind": "MultiTenantConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "multi-tenant-operator"
            },
            "name": "multitenantconfig-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "tenantconfig.openshift.io/v1alpha1",
          "kind": "NamespaceLimitRange",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "multi-tenant-operator"
            },
            "name": "namespacelimitrange-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "tenantconfig.openshift.io/v1alpha1",
          "kind": "NamespaceResourceQuota",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "multi-tenant-operator"
            },
            "name": "namespaceresourcequota-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-03-24T10:23:00Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: multi-tenant-operator.v0.1.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiTenantConfig is the Schema for the multitenantconfigs API.
      displayName: Multi Tenant Config
      kind: MultiTenantConfig
      name: multitenantconfigs.tenant.openshift.io
      version: v1alpha1
    - description: NamespaceLimitRange is the Schema for the namespacelimitranges
        API.
      displayName: Namespace Limit Range
      kind: NamespaceLimitRange
      name: namespacelimitranges.tenantconfig.openshift.io
      version: v1alpha1
    - kind: NamespaceResourceQuota
      name: namespaceresourcequotas.tenantconfig.openshift.io
      version: v1alpha1
  description: asd
  displayName: multi-tenant-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - limitranges
          - namespaces
          - resourcequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - argoproj.io
          resources:
          - appprojects
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenant.openshift.io
          resources:
          - multitenantconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenant.openshift.io
          resources:
          - multitenantconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - tenant.openshift.io
          resources:
          - multitenantconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tenantconfig.openshift.io
          resources:
          - namespacelimitranges
          - namespaceresourcequotalists
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: multi-tenant-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: multi-tenant-operator
          control-plane: controller-manager
        name: multi-tenant-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: multi-tenant-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: multi-tenant-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: quay.io/redhat-consulting-services/multi-tenant-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: multi-tenant-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: multi-tenant-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - tenant
  - multi tenant
  - multi-tenant
  - multi-tenant-operator
  - multi tenant operator
  - multi tenancy
  - multi-tenancy
  - multi-tenancy-operator
  - multi tenancy operator
  links:
  - name: Multi Tenant Operator
    url: https://github.com/redhat-consulting-services/multi-tenant-operator
  maintainers:
  - email: lsteinha@redhat.com
    name: Leon Steinhäuser
  - email: olindhol@redhat.com
    name: Oscar Lindholm
  maturity: alpha
  minKubeVersion: 1.32.0
  provider:
    name: redhat-consulting-services
    url: https://github.com/redhat-consulting-services
  version: 0.1.1
