---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - limitranges
  - namespaces
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.openshift.io
  resources:
  - multitenantconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.openshift.io
  resources:
  - multitenantconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tenant.openshift.io
  resources:
  - multitenantconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tenantconfig.openshift.io
  resources:
  - namespacelimitranges
  - namespaceresourcequotas
  verbs:
  - get
  - list
  - watch
