# This rule is not used by the project multi-tenant-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tenant.openshift.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multi-tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenant-multitenantconfig-viewer-role
rules:
- apiGroups:
  - tenant.openshift.io
  resources:
  - multitenantconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenant.openshift.io
  resources:
  - multitenantconfigs/status
  verbs:
  - get
